baseURL = 'https://steenpapierschaar.tech/'
languageCode = 'en-us'
title = 'SteenPapierSchaar.tech'

# Set theme for website to Hugo Book
theme = 'hugo-book'

# Enable Git info for author of website pages
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
    # Set the theme to light or dark
    BookTheme = 'auto'

    BookRepo = 'https://github.com/steenpapierschaar-tech/steenpapierschaar-tech'
    BookCommitPath = 'commit'
    BookEditPath = 'edit/main/website'
    BookSection = '*'

[menu]
#  title = 'Links'
#[[menu.before]]
#  name = "Links"
[[menu.after]]
  name = "Github"
  url = "https://github.com/steenpapierschaar-tech/steenpapierschaar-tech"
  weight = 10